//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleShopWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.carrito = new HashSet<carrito>();
            this.carrito_pc = new HashSet<carrito_pc>();
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string activo { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> precio { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<carrito> carrito { get; set; }
        public virtual ICollection<carrito_pc> carrito_pc { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
    }
}
