//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleShopWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.carrito = new HashSet<carrito>();
            this.venta = new HashSet<venta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string contrasenia { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual ICollection<carrito> carrito { get; set; }
        public virtual rol rol { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
