//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleShopWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> id_origen { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual origen origen { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
